# NumPy Python Library.
 NumPy(Numerical Python) is an open sourcePython library that is very useful in Mathematical and Scintific programming and computations.

-NumPy is used for working with a powerful N-dimentional array object.
-NumPy is incredible library to perform mathmetical & Statical operations due to its 
 fast and memeory efficient.

# Import NumPy 

In [1]:
import numpy as np 

## ndarray object
### The basic ndarray is created using as array function in NumPy 

In [2]:
a=[1,2,3,4,5,6]
b=np.array(a)
b

array([1, 2, 3, 4, 5, 6])

## Creating NumPy Arrays from a list

In [3]:
anew=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [4]:
#Shape
anew.shape

(2, 5)

In [5]:
#print Dimensions
anew.ndim

2

In [6]:
#size
anew.size

10

In [7]:
anew

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
#matrix to array
an=np.array([[1,2,3],[4,5,6],[7,8,9]])
an

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# functions for creating arrays 

In [9]:
a=np.arange(20)# start,end( exclusive ), step

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
#Reshape any array
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
##linespace-REturn evenly spaced over asoecified interval
a=np.linspace(0,10,5)# (start,end,num of sample)

In [13]:
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
#random.randint-Returnes random integers from start (inclusive ) to end (exclusive)
a=np.random.randint(1,50,5)

In [15]:
a

array([35, 43, 27,  8, 13])

In [16]:
#Zeroes -Generates arrays of zero 
np.zeros((4,4))+1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
a=np.array([[1,2,3],[4,5,6]])

In [18]:
#Flattening-Converting nd array to 1D array
a.ravel()

array([1, 2, 3, 4, 5, 6])

### Transpose 

In [19]:
a=np.array([[1,2,3],[4,5,6]])
c=a.T

In [20]:
c

array([[1, 4],
       [2, 5],
       [3, 6]])

## Copy array

In [21]:
a=np.array([1,2,3,4])
b=a# Shallow Copy 
print(b)
print(a)

[1 2 3 4]
[1 2 3 4]


In [22]:
a=np.array([1,2,3,4])
b=a.copy()#Deep Copy 
b[0]=100
print(b)
print(a)

[100   2   3   4]
[1 2 3 4]


## Add/Remove operations on numpy array

In [23]:
a=np.array([1,2,3,4])
a=np.append(a,[7,8,9])
a

array([1, 2, 3, 4, 7, 8, 9])

In [24]:
a=np.delete(a,2)
a

array([1, 2, 4, 7, 8, 9])

In [25]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [26]:
a[1,2]=7 # assigning value 

In [27]:
a

array([[1, 0, 0],
       [0, 2, 7],
       [0, 0, 3]])

## Indexing with an array of integers 

In [28]:
a=np.arange(10,101,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [29]:
a[2]

30

In [30]:
a[[2,3,4,5,6]]

array([30, 40, 50, 60, 70])

In [31]:
a[2]=100

In [32]:
a[[1,2]]=1000000

In [33]:
a=np.arange(20)

In [34]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Mask indexing or Fancy indexing

In [35]:
a=np.array([15,6,2,16,20,25,])
a%2==0

array([False,  True,  True,  True,  True, False])

In [36]:
a[a%2==0]

array([ 6,  2, 16, 20])

## slicing  

In [37]:
a=np.arange(4,20)

In [38]:
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
a[1:20:2]

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [40]:
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

## arthemetic operations 

In [41]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [42]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [43]:
a=[[1,2,3],[4,5,6],[1,5,3]]
b=[[2,3,4],[2,4,6],[1,2,6]]
c=np.matmul(a,b)
c

array([[ 9, 17, 34],
       [24, 44, 82],
       [15, 29, 52]])

## Comarision operations 

In [44]:
a==b

False

In [45]:
a>b

False

In [46]:
np.array_equal(a,b)

False

In [47]:
np.array_equal(a,c)

False

# Mathematical operations 

In [48]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [0.        , 1.60943791, 1.09861229]])

In [49]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349],
       [  2.71828183, 148.4131591 ,  20.08553692]])

In [50]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.84147098, -0.95892427,  0.14112001]])

In [51]:
np.array_equal(a,b)

False

In [52]:
#sorting

In [53]:
a=np.sort([4,5,2,1,6])

In [54]:
a

array([1, 2, 4, 5, 6])